<a href="https://colab.research.google.com/github/47252uni/AI_lab/blob/main/lab_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
print("Numpy Version",np.__version__)
arr = np.array([2,4,5,6,8])
print(arr)

Numpy Version 2.0.2
[2 4 5 6 8]


In [3]:
import numpy as np

arr = np.array([1, 2, 3])

print("Type of array", type(arr))
print("Dimension of array arr is", arr.ndim)

d0 = np.array(23)
print("Dimension of array d0 is", d0.ndim)

fruit_list = ["Apple", "Mango", "Banana"]
print(fruit_list)

print("Type of fruit list is ", type(fruit_list))

fruit_list = np.array(fruit_list)
print("Type of fruit list is ", type(fruit_list))


Type of array <class 'numpy.ndarray'>
Dimension of array arr is 1
Dimension of array d0 is 0
['Apple', 'Mango', 'Banana']
Type of fruit list is  <class 'list'>
Type of fruit list is  <class 'numpy.ndarray'>


In [4]:
import numpy as np
A = np.array([8, 4, 6, 0, 2])
print(A)
B = np.array([[1, 2, 3], [4, 5, 6]])
print(B)
C = np.array([[[1, 2, 3], [4, 5, 6], [14, 15, 16]]])
print(C)

C_dimensions = C.ndim
print(C_dimensions)


[8 4 6 0 2]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]
  [14 15 16]]]
3


In [5]:
import numpy as np

d1 = np.array([6, 8, 1, 2])
print("The dimension of array d1 is ", d1.ndim)
print("Elements of array d1 are ", d1)

d2 = np.array([[58, 69, 34, 45], [25, 65, 68, 99], [56, 98, 1, 2]])

print("Elements of array d2 are ", d2)
print("The dimension of array d2 is ", d2.ndim)

print("Element at (1,0) row 1 column 0 is ", d2[1,0])


The dimension of array d1 is  1
Elements of array d1 are  [6 8 1 2]
Elements of array d2 are  [[58 69 34 45]
 [25 65 68 99]
 [56 98  1  2]]
The dimension of array d2 is  2
Element at (1,0) row 1 column 0 is  25


In [8]:
import numpy as np

d3array = np.array([
    [   # Depth 0
        [1, 2, 3],    # Row 0
        [4, 5, 6],    # Row 1
    ],
    [   # Depth 1
        [7, 8, 9],    # Row 0
        [10, 11, 12], # Row 1
    ],
    [   # Depth 2
        [13, 14, 15], # Row 0
        [16, 17, 18], # Row 1
    ]
])

print("The dimension of array d3array is ", d3array.ndim)
print(d3array)

# d3array[depth_index][row_index][column_index]
item = d3array[2][0][0]  # Depth 2, Row 0, Column 0
print("Item at d3array[2][0][0] is: ", d3array[2][0][0])


The dimension of array d3array is  3
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
Item at d3array[2][0][0] is:  13


In [7]:
# Numpy array slicing
import numpy as np

d1 = np.array([6,8,1,2,54,5,3])   # 1-D Array
print("Elements of array d1 are ", d1)

print("Elements slicing 'd1[1:5]' ", d1[1:5])   # 1-D Array slicing "The result includes the start index, excludes the end index"
print("Elements slicing 'd1[:3]' ", d1[:3])     # Slice elements form start index[0] to index[3], index [3] excluded
print("Elements slicing 'd1[3:]' ", d1[3:])     # Slice elements form index[3] to last index
print("Elements slicing 'd1[-3:-1]' ", d1[-3:-1])  # Slice elements (negative slicing) form index[-3] to index[-1], index[-1] excluded

d2 = np.array([[5,9,3,4],[21,65,8,99],[56,98,1,2]])   # 2-D Array
print("Elements of array d2 are ", d2)

print("Elements slicing 'd2[0,1:3]' ", d2[0,1:3])   # 2-D Array slicing : Slice elements form array[0], index[1] to index[3], index[3] excluded


Elements of array d1 are  [ 6  8  1  2 54  5  3]
Elements slicing 'd1[1:5]'  [ 8  1  2 54]
Elements slicing 'd1[:3]'  [6 8 1]
Elements slicing 'd1[3:]'  [ 2 54  5  3]
Elements slicing 'd1[-3:-1]'  [54  5]
Elements of array d2 are  [[ 5  9  3  4]
 [21 65  8 99]
 [56 98  1  2]]
Elements slicing 'd2[0,1:3]'  [9 3]


In [6]:

print("Array d1 slicing with step:d1[1:6:2] ", d1[1:6:2])


Array d1 slicing with step:d1[1:6:2]  [8 2]


In [9]:
import numpy as np


a2 = np.array([[11, 22, 33, 44],
               [14, 15, 16, 17]])


a2shape = a2.shape

print("Shape of the array:", a2shape)


Shape of the array: (2, 4)


In [10]:
import numpy as np

a2D = np.array([[1, 2], [3, 4]])
print("Array a2D", a2D)

# array flatten through reshape
print(a2D.reshape(-1))


Array a2D [[1 2]
 [3 4]]
[1 2 3 4]


In [11]:
import numpy as np

# b as a view of a
a = np.array([1, 2, 3, 4, 5, 6])
print("Array a", a)

b = a[:2]
print("Array b", b)

b += 1
print("Array b after increment if a", b)
print("Array a =", a, "; array b =", b)

# create a new array, using numpy copy array
a = np.array([1, 2, 3, 4])
b = a[:2].copy()
b += 1

print("a =", a, "b =", b)


Array a [1 2 3 4 5 6]
Array b [1 2]
Array b after increment if a [2 3]
Array a = [2 3 3 4 5 6] ; array b = [2 3]
a = [1 2 3 4] b = [2 3]


In [12]:
import numpy as np

d1 = np.array([6, 8, 1, 2, 54, 5, 3])

for x in d1:
    print(x)


6
8
1
2
54
5
3


In [13]:
import numpy as np

# 2-D Array
d2 = np.array([[58, 69, 34, 45],
               [25, 65, 68, 99],
               [56, 98, 1, 2]])

print("Elements of array d2 are", d2)

for x in d2:
    for i in x:
        print(i)


Elements of array d2 are [[58 69 34 45]
 [25 65 68 99]
 [56 98  1  2]]
58
69
34
45
25
65
68
99
56
98
1
2


In [14]:
import numpy as np

d3 = np.array(np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]],
    [[13, 14, 15], [16, 17, 18]]
]))

print("The dimension of array d3 is", d3.ndim)
print(d3)

for x in d3:
    for y in x:
        for z in y:
            print(z)


The dimension of array d3 is 3
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18


In [15]:
import numpy as np

d2 = np.array([[58,69,34,45],[25,65,68,99],[56,98,1,2]]) #2-D Array
print("Elements of array d2 are ",d2)
for x in np.nditer(d2):
  print(x)

Elements of array d2 are  [[58 69 34 45]
 [25 65 68 99]
 [56 98  1  2]]
58
69
34
45
25
65
68
99
56
98
1
2


In [16]:
import numpy as np

arr1 = np.array([1,2,3,4,5,6])
print("Array 1: ",arr1)

arr2 = np.array([7,8,9,10,11,12])
print("Array 2: ",arr2)

arr3 = np.concatenate((arr1,arr2))
print ("Concatenated array: arr3",arr3)

Array 1:  [1 2 3 4 5 6]
Array 2:  [ 7  8  9 10 11 12]
Concatenated array: arr3 [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [17]:
import numpy as np

arr1 = np.array([1,2,3])
print("Array 1: ",arr1)

arr2 = np.array([7,8,9])
print("Array 2: ",arr2)

arr3 = np.stack((arr1,arr2), axis=1)
print ("Concatenated array through stack: arr3",arr3)

Array 1:  [1 2 3]
Array 2:  [7 8 9]
Concatenated array through stack: arr3 [[1 7]
 [2 8]
 [3 9]]


In [18]:
import numpy as np

arr1 = np.array([1,2,3,4,5,6])
splitarr = np.array_split(arr1,3)
print("Array 1 split into 3 arrays",splitarr)
print("Array 1",splitarr[0])
print("Array 2",splitarr[1])
print("Array 3",splitarr[2])

Array 1 split into 3 arrays [array([1, 2]), array([3, 4]), array([5, 6])]
Array 1 [1 2]
Array 2 [3 4]
Array 3 [5 6]


In [19]:
import numpy as np

arr1 = np.array([1,2,3,4,5,6])
x = np.where(arr1 == 4)
print("Search index of 4",x)

Search index of 4 (array([3]),)


In [20]:
import numpy as np

arr2 = np.array([3,4,5,6,7,8])
x = np.searchsorted(arr2, 6)
print("Index of 6 is",x)

Index of 6 is 3


In [21]:
import numpy as np

arr2 = np.array([3,4,5,6,7,8])
x = np.searchsorted(arr2, 6)
print("Index of 6 is",x)

alparr = np.array(["Cherry", "Sugar", "Floor", "Cooking Oil"])
print(alparr)
print("Sorted array",np.sort(alparr))

Index of 6 is 3
['Cherry' 'Sugar' 'Floor' 'Cooking Oil']
Sorted array ['Cherry' 'Cooking Oil' 'Floor' 'Sugar']


In [22]:
import numpy as np

arr = np.array([[58,69,34,45],[25,65,68,99],[56,98,1,2]])
mask = arr > 45
new_array = arr[mask]
print(new_array) # Output: [58 69 65 68 99 56 98]

[58 69 65 68 99 56 98]


**Lab task lab_no_03**

In [23]:
import numpy as np

arr = np.arange(2,11).reshape(3,3)
arr = arr.astype(float)
print("3x3 Matrix (float): ",arr)

flat_arr = arr.flatten()
print("Flattened array: ",flat_arr)

print("Maximum value: ",flat_arr.max())
print("Minimum value: ",flat_arr.min())

3x3 Matrix (float):  [[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]
Flattened array:  [ 2.  3.  4.  5.  6.  7.  8.  9. 10.]
Maximum value:  10.0
Minimum value:  2.0
